baseURL = "https://pniskala.github.io/"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-PaperMod"

# website title
title = "Paavo Niskala"

# push to the right directory
publishDir = "docs"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Paavo Niskala"
description = "Paavo Niskala"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Paavo Niskala"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

#   [params.assets]
#   favicon = "<link / abs url>"
#   favicon16x16 = "<link / abs url>"
#   favicon32x32 = "<link / abs url>"
#   apple_touch_icon = "<link / abs url>"
#   safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Hi, I am Paavo Niskala."
  subtitle = "I am a Jack of all trades, master of some."
  imageUrl = "images/paavo-hattu.png"
  imageWidth = 160
  imageHeight = 160
  imageTitle = "That's Paavo."

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts/"

    # [[params.profileMode.buttons]]
    # name = "Tags"
    # url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/pniskala/"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/Paavi"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

  [params.cover]
  hidden = false
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

# [[menu.main]]
# identifier = "posts"
# name = "posts"
# url = "/posts/"
# weight = 10

# [[menu.main]]
# identifier = "categories"
# name = "categories"
# url = "/categories/"
# weight = 10

# [[menu.main]]
# identifier = "tags"
# name = "tags"
# url = "/tags/"
# weight = 20

# [[menu.main]]
# identifier = "example"
# name = "example.org"
# url = "https://example.org"
# weight = 30

[markup.highlight]
noClasses = false

  